server:
  port: 8080
spring:
  application:
    name: "franchise-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
    active: "${ENVIRONMENT:dev}"
  jackson:
    deserialization:
      fail-on-unknown-properties: false
logging:
  structured:
    format:
      console: "ecs"
  level:
    root: "INFO"
    '[co.com.bancolombia]': "${LOG_LEVEL:INFO}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  dynamodb:
    franchiseTable: "franchise-table-dev"
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  show-actuator: true
